
spring:
    #数据源相关配置
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        test:
            url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
        password: root
        username: root